lenguadepiton/urls.py
from django.contrib import admin
from django.urls import include, path

#agregado de tensorflow tutorial
from django.conf.urls import url
from problematica3 import views




#agregado del tutorial pytorch
from django.conf.urls.static import static
from django.conf import settings
#from . import views

app_name = 'lenguadepiton'


urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path('problematica3/', include("problematica3.urls")),
    path('users/', include("users.urls")),
    path('newyear/', include("newyear.urls")),
    path('pruebacarlo/', include("pruebacarlo.urls")),
    path('tasks/', include("tasks.urls")),
    
   
   
]
"""
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)"""

tasks/urls.py
from django.urls import path


from . import views

app_name ="tasks"

urlpatterns =[
    
    path("", views.index, name="index"),
    path("add", views.add, name="add")
    
]
    

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse


#tasks = ["foo", "bar", "baz"]
#tasks =[]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority",min_value=1, max_value=10)
    
    

# Create your views here.

def index(request):
    
    if "tasks" not in request.session:
        request.session["tasks"] = []
    
    return render(request, "tasks/index.html",{
  #     "tasks": tasks 
          "tasks": request.session["tasks"]
        
    })

def add(request):
    
    if request.method =="POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
       #  tasks.append(task)
            request.session["tasks"]  += [task]   
          #  return HttpResponseRedirect(reverse("tasks:index")) 
            return redirect('tasks:index')
        else:
            return render(request, "tasks/add.html", {
                "form": form
                
            })
    
    
    return render(request, "tasks/add.html",{
        "form": NewTaskForm()
        
    })

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}



{% block body %}
        <h1> Add Task </h1>
      <form action="{% url 'tasks:add' %}" method="post">
          {% csrf_token %}
          {{ form }}
          
           <!-- <input type="text" name="task"> -->
            <input type="submit">
            
        
        </form>
<a href="{% url 'tasks:index' %}"> View Tasks </a>
   {% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1> Tasks </h1>



        <ul>
            {% for task in tasks %}
            <li>{{ task }}</li>
            {% empty %}
             <li>No tasks.<li>
            
            {% endfor %}
            
            
        </ul>

<a href="{%url 'tasks:add' %}">Add a new Task</a>

 {% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang ="en">
    <head>
        <title>
           Tasks
        </title>
  </head>
    <body>
        
        {% block body %}
        {%  endblock  %}
        
    </body>
    
</html> 